#version 430 core
layout (local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(r8, binding = 0) uniform readonly image3D brickActiveTex;
layout(r8, binding = 3) uniform readonly image3D brickSignTex;
layout(rgba32f, binding = 1) uniform writeonly image3D lookupOut;
layout(rgba32f, binding = 2) uniform writeonly image3D reverseLookupOut;

layout(std430, binding = 1) buffer AllocCounter {
    uint nextSlot;
};

uniform vec3 _GridResolution;
uniform vec3 _PoolGridDim;
uniform int BRICK_STORE;

float isActive(ivec3 brickIndex) {
    return imageLoad(brickActiveTex, brickIndex).r +
    imageLoad(brickActiveTex, brickIndex + ivec3(1, 0, 0)).r +
    imageLoad(brickActiveTex, brickIndex + ivec3(-1, 0, 0)).r +
    imageLoad(brickActiveTex, brickIndex + ivec3(0, 1, 0)).r +
    imageLoad(brickActiveTex, brickIndex + ivec3(0, -1, 0)).r +
    imageLoad(brickActiveTex, brickIndex + ivec3(0, 0, 1)).r +
    imageLoad(brickActiveTex, brickIndex + ivec3(0, 0, -1)).r;
}

void main() {
    ivec3 brickIndex = ivec3(gl_GlobalInvocationID);
    ivec3 gridRes = ivec3(_GridResolution);
    if (any(greaterThanEqual(brickIndex, gridRes))) return;

    float _active = isActive(brickIndex);
    if (_active < 0.5) {
        float brickSign = imageLoad(brickSignTex, brickIndex).r;
        float w = (brickSign > 0.5) ? -1.0 : 0.0; // solid : empty
        imageStore(lookupOut, brickIndex, vec4(0.0, 0.0, 0.0, w));
        return;
    }

    uint slot = atomicAdd(nextSlot, 1u);
    ivec3 poolGridDim = ivec3(_PoolGridDim);
    int poolCapacity = poolGridDim.x * poolGridDim.y * poolGridDim.z;

    if (int(slot) >= poolCapacity) {
        imageStore(lookupOut, brickIndex, vec4(0.0));
        return;
    }

    ivec3 poolBrickCoord = ivec3(
        int(slot) % poolGridDim.x,
        (int(slot) / poolGridDim.x) % poolGridDim.y,
        int(slot) / (poolGridDim.x * poolGridDim.y)
    );
    vec3 poolOrigin = vec3(poolBrickCoord * BRICK_STORE);

    imageStore(lookupOut, brickIndex, vec4(poolOrigin, 1.0));
    imageStore(reverseLookupOut, poolBrickCoord, vec4(vec3(brickIndex), 1.0));
}