#version 430 core

layout (local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(rgba32f, binding = 0) uniform readonly image3D finalSeeds;
layout(r8, binding = 1) uniform readonly image3D signTex;
layout(r16f, binding = 2) uniform writeonly image3D volumeTex;

uniform vec3 _WorldMin;
uniform vec3 _WorldMax;
uniform vec3 _Resolution;

vec3 getWorldPos(vec3 texel) {
    vec3 uvw = (vec3(texel) + 0.5) / vec3(_Resolution);
    vec3 worldPos = _WorldMin + uvw * (_WorldMax - _WorldMin);
    return worldPos;
}

void main() {
    ivec3 texel = ivec3(gl_GlobalInvocationID);

    vec3 pos = getWorldPos(texel);
    vec3 seedTexel = imageLoad(finalSeeds, texel).xyz;
    vec3 seedPos = getWorldPos(seedTexel);

    float dist = abs(distance(pos, seedPos));

    float sign = imageLoad(signTex, texel).r; // 1.0 = inside, 0.0 = outside per your classify convention
    float signedDist = (sign > 0.5) ? -dist : dist;
    imageStore(volumeTex, texel, vec4(signedDist));
}