#version 430 core

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(r16f, binding = 0) uniform writeonly image3D noiseOut;

uniform vec3 _Resolution;
uniform float _Frequency;
uniform int _Seed;

float hash3D(vec3 p)
{
    p += vec3(
        float(_Seed) * 0.123,
        float(_Seed) * 0.456,
        float(_Seed) * 0.789
    );

    p = fract(p * 0.1031);
    p += dot(p, p.yzx + 33.33);

    return fract((p.x + p.y) * p.z);
}

float smoothNoise3D(vec3 p)
{
    vec3 i = floor(p);
    vec3 f = fract(p);

    vec3 u = f * f * (3.0 - 2.0 * f);

    float a = hash3D(i + vec3(0, 0, 0));
    float b = hash3D(i + vec3(1, 0, 0));
    float c = hash3D(i + vec3(0, 1, 0));
    float d = hash3D(i + vec3(1, 1, 0));
    float e = hash3D(i + vec3(0, 0, 1));
    float g = hash3D(i + vec3(1, 0, 1));
    float h = hash3D(i + vec3(0, 1, 1));
    float j = hash3D(i + vec3(1, 1, 1));

    return mix(
    mix(mix(a, b, u.x), mix(c, d, u.x), u.y),
    mix(mix(e, g, u.x), mix(h, j, u.x), u.y),
    u.z
    );
}

void main()
{
    ivec3 texel = ivec3(gl_GlobalInvocationID);

    // bounds check
    if (any(greaterThanEqual(texel, _Resolution)))
    return;

    // One noise period across the texture
    vec3 uv = (vec3(texel) + 0.5) / vec3(_Resolution);

//    float value = smoothNoise3D(uv * _Frequency);

    float value = smoothNoise3D(uv * _Frequency);
    imageStore(noiseOut, texel, vec4(value));
}